// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDBf_KMMpJn1toULtgjU2J50Y4sCYJ8ogE',
    appId: '1:906598880802:web:b0211ba0a046d35968dc7b',
    messagingSenderId: '906598880802',
    projectId: 'easyshopping-e5ffe',
    authDomain: 'easyshopping-e5ffe.firebaseapp.com',
    storageBucket: 'easyshopping-e5ffe.appspot.com',
    measurementId: 'G-6H30EB0X5T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCd3g4D5jfJDKRGcyc5oPUCB8CWdSCZc0g',
    appId: '1:906598880802:android:1f15fc374a73065668dc7b',
    messagingSenderId: '906598880802',
    projectId: 'easyshopping-e5ffe',
    storageBucket: 'easyshopping-e5ffe.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC0g7dEc_xW-qqsidAeLp1FNYfHwiDcWJE',
    appId: '1:906598880802:ios:a4f68e8fb98826da68dc7b',
    messagingSenderId: '906598880802',
    projectId: 'easyshopping-e5ffe',
    storageBucket: 'easyshopping-e5ffe.appspot.com',
    iosBundleId: 'com.example.eCommerce',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC0g7dEc_xW-qqsidAeLp1FNYfHwiDcWJE',
    appId: '1:906598880802:ios:028f5a23b99a3bfc68dc7b',
    messagingSenderId: '906598880802',
    projectId: 'easyshopping-e5ffe',
    storageBucket: 'easyshopping-e5ffe.appspot.com',
    iosBundleId: 'com.example.eCommerce.RunnerTests',
  );
}
